version: '3'
services:
  mongo:
    image: 'mongo:latest'
    volumes:
      - ./database:/data/db
    ports:
      - '37017:27017'
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:8080
  api:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/codegames
      - PORT=8080
    ports:
      - '8080:8080'
      - '9229:9229'